### ISSUE TITLE
Different json response for the same evolution-chain request

### ISSUE THREAD

**Issue by pedrorault** [PokeAPI/pokeapi#515] opened 2020-08-07 18:56 UTC
The difference seems to be caused by the slash at the end.
I haven't encountered this difference in other requests, so I guess it's not intentional.
In one response, the evolves_to is not nested like the others.

| Wrong?| Correct |
|---------|-------|
| https://pokeapi.co/api/v2/evolution-chain/1       |    https://pokeapi.co/api/v2/evolution-chain/1/   |

![pokeapi](https://user-images.githubusercontent.com/52670501/89678537-baa8c100-d8c5-11ea-9407-0e63b5fc5358.png)

Thanks

**Comment by Naramsim** [comment] 2020-08-07 19:20
You're absolutely right! Does it happen only for bulbasaur->venusaur? I'll look into it

**Comment by Naramsim** [comment] 2020-08-07 19:22
PS: on my side, it happens always no matter the slash

**Comment by Naramsim** [comment] 2020-08-07 19:40
Nuts, this issue is present since even before we merged https://github.com/PokeAPI/pokeapi/pull/485.

**Comment by Naramsim** [comment] 2020-08-07 19:45
Maybe @phrasmotica,  could guess something. A couple of months ago he helped us with Wurmple's evolutions. Maybe for him, it could be easy.

**Comment by C-Garza** [comment] 2020-08-08 02:08
I did some testing @Naramsim for evolution-chain/1 between #513 and #514. I built them both to an sqlite and postgresql db. 

On the sqlite db, it works as intended with `evolves_to` being nested, like the right hand side of the picture in @pedrorault comment. But on the postgresql db, the api endpoint returned the wrong result, the left side of the image, in #514 but the correct right side of the image in #513. 

I haven't looked into the functions yet, but maybe some data in the csv's updated in #514 are causing the issue?

Also, I found an unrelated issue looking at the [pokemon_species.csv](https://github.com/PokeAPI/pokeapi/blob/f91b6b6b1af509be90d8b3d1ce0f0ff1f40d360f/data/v2/csv/pokemon_species.csv) in the updated Veekun data. The order variable set in this function in the [build.py](https://github.com/PokeAPI/pokeapi/blob/ad3c43623dc498ba75a6168b76fe67a75012c8c4/data/v2/build.py#L1263-L1282) script is no longer set to the order column in the csv, but now the is_legendary column.

**Comment by C-Garza** [comment] 2020-08-08 02:47
Actually I think having the wrong order value I mentioned above is actually the issue for this because I think this function in the [serializers.py](https://github.com/PokeAPI/pokeapi/blob/ad3c43623dc498ba75a6168b76fe67a75012c8c4/pokemon_v2/serializers.py#L3127-L3147) script uses the order to sort the pokemon. I'm going to try and see if this is the cause.

**Comment by C-Garza** [comment] 2020-08-08 03:00
Yup, that seems to be the issue. Changing line 1281 in this function from [build.py](https://github.com/PokeAPI/pokeapi/blob/ad3c43623dc498ba75a6168b76fe67a75012c8c4/data/v2/build.py#L1263-L1282) to the correct column number (18 instead of 16) fixes the issue. Should I make a pull request?

**Comment by Naramsim** [comment] 2020-08-08 12:48
> Actually I think having the wrong order value I mentioned above is actually the issue for this because I think this function in the [serializers.py](https://github.com/PokeAPI/pokeapi/blob/ad3c43623dc498ba75a6168b76fe67a75012c8c4/pokemon_v2/serializers.py#L3127-L3147) script uses the order to sort the pokemon. I'm going to try and see if this is the cause.

Ahhh, true! I've also seen that they added some columns! If that's the issue, could you please open a PR towards our `staging` branch? Thanks SO much for the analysis!

**Comment by Naramsim** [comment] 2020-08-08 16:06
Hi, @C-Garza, it works! Thanks a lot!, Fieww, you saved us a lot of hassles. Could you please then open the PR so it appears it was you that fixed the issue?

Thanks

**Comment by C-Garza** [comment] 2020-08-08 21:23
No problem, I've made the pull request now 😄.

**Closed** 2020-08-08 22:05 UTC
