### ISSUE TITLE
Improvement for Berry and Flavor

### ISSUE THREAD

**Issue by eglain** [PokeAPI/pokeapi#113] opened 2016-02-27 20:54 UTC
I am currently working on a data import into a RDB and I am in struggle with the mapping for Berry and BerryFlavor.

The mapping between these two resources is split into two resoruces (BerryFlavorMap and FlavorBerryMap) with the reference of the other resource plus the potency.

Would it be possible to merge these two resources into one? That would make the handling much nicer.

BerryFlavorMap
- Berry (reference to the relevent Berry)
- Flavor (reference to the relevent BerryFlavor)
  -Potency

**Comment by zaneadix** [comment] 2016-03-02 17:07
@eglain I'm really not sure where the issue is. They couldn't be merged together because they're the exact opposite of one another. They both server as being a reverse lookup of the other. It sounds like you're trying to pull the data down and store it in your own db? If thats the case you wouldnt want to store these values. These maps are built from foreign key relations so you would just have a table for berries, a table for berry flavors and have a foreign key relation from one to the other.

Let me know if I've missed something

**Closed** 2017-06-12 12:52 UTC
Labels: question
