### ISSUE TITLE
Pokemon types are inverted

### ISSUE THREAD

**Issue by tien** [PokeAPI/pokeapi#379] opened 2018-10-03 01:28 UTC
All the pokemon secondary type appear as the first element in the type list.
The order is correct when I ran a local Django instance

**Comment by tdmalone** [comment] 2018-10-03 01:41
Hm.. interesting. Ordering of array items generally isn't guaranteed - but can you post a copy of what you're seeing compared with what you want to see?

**Comment by crazycat9x** [comment] 2018-10-03 01:45
```json
 "types": [
        {
            "slot": 2,
            "type": {
                "name": "fairy",
                "url": "https://pokeapi.co/api/v2/type/18/"
            }
        },
        {
            "slot": 1,
            "type": {
                "name": "water",
                "url": "https://pokeapi.co/api/v2/type/11/"
            }
        }
    ]
```
When I ran it locally it's
```json
 "types": [
        {
            "slot": 1,
            "type": {
                "name": "water",
                "url": "https://pokeapi.co/api/v2/type/11/"
            }
        },
        {
            "slot": 2,
            "type": {
                "name": "fairy",
                "url": "https://pokeapi.co/api/v2/type/18/"
            }
        }
    ]
```

**Comment by tdmalone** [comment] 2018-10-03 02:03
Ok, so what you need to do here is use the `slot` to determine which should be the first type.

I agree, it would be ideal if they came out in order, but arrays are generally an unordered collection - so the ordering can't be guaranteed.

Having said that, I'm pinging @sargunv in case this is a regression due to us moving to statically generated files. Whether or not it's a fixable regression... probably depends on how complex it is. In general though - don't rely on the order ;). You _can_, however, rely on the slot number.

**Comment by sargunv** [comment] 2018-10-03 02:05
That's really weird, ditto should be preserving order of arrays during a clone. But yeah, the API spec doesn't guarantee any specific order, use slot to determine order.

**Comment by crazycat9x** [comment] 2018-10-03 05:28
I'll stick with the slot num for now just to be safe. But I still can't help but think that something is wrong since all the types array is flipped 🤔

**Comment by Naramsim** [comment] 2020-08-12 20:24
Closing since by default `list`s are not guaranteed to be ordered.

**Closed by Naramsim** 2020-08-12 20:24 UTC
