### ISSUE TITLE
Meltan and Melmetal Pokémon Missing

### ISSUE THREAD

**Issue by shilangyu** [PokeAPI/pokeapi#414] opened 2019-02-03 15:00 UTC
Database is missing Meltan (808) and Melmetal (809) originally discovered in Pokemon GO, usable in Pokemon Lets Go.

**Comment by stl1988** [comment] 2019-05-13 23:34
They are still missing - and Pokémon Let's Go is out for a half year now.

**Comment by cmmartti** [comment] 2019-05-13 23:42
As mentioned in the [issue template](https://github.com/PokeAPI/pokeapi/blob/master/ISSUE_TEMPLATE), please forward this complaint to [Veekun](https://github.com/veekun/pokedex/issues). We don't keep track of this data ourselves. We just use their data.

Note that Go and Let's Go are not part of the main game series, and Veekun generally doesn't deal with the spin-offs. But this specific case might be different.

**Comment by stl1988** [comment] 2019-05-13 23:48
Pokémon Let's Go Pikachu and Let's Go Eevee ARE part of the main series. That's been confirmed multiple times now.

This japanese page from the official japanese Pokémon website confirms it aswell.

**Comment by cmmartti** [comment] 2019-05-14 00:05
Sure, but as I understand it, Let's Go is a significant departure from the regular games, and probably won't fit neatly into Veekun's database. (I haven't played it.)

**Comment by stl1988** [comment] 2019-05-14 00:10
The capture mechanics and Pokémon appearing on the overworld may be different and also the games only include Kanto Pokémon and Meltan/Melmetal, but since they are a remake of Pokémon Yellow, it's of course part of the main series. You even have normal trainer battles, gyms, evil team (Team Rocket) and the Elite Four plus champ. Everything which makes a mainline Pokémon game is in these games.

Of course, the Pokémon Go app is not part of the main series.

**Comment by tdmalone** [comment] 2019-05-15 07:14
I'm going to close this, as once (if) the data is added to Veekun it will be available here in PokeAPI too :)

**Closed by tdmalone** 2019-05-15 07:14 UTC
