### ISSUE TITLE
Mistake in Data of Pikachu in weight

### ISSUE THREAD

**Issue by P3RFECT01** [PokeAPI/pokeapi#759] opened 2022-10-19 09:29 UTC
Steps to Reproduce:

1. I was working with API using Pikachu for testing but when, I received weight of Pikachu, It is giving weight as 60 but original weight of Pikachu is 6.0kg or 6kg.

![image](https://user-images.githubusercontent.com/99315109/196652740-15b67318-9737-431d-8684-aa0104d1ffea.png)

Official Data:
![image](https://user-images.githubusercontent.com/99315109/196653319-568ba973-8f82-4f74-8075-05cc18a0d479.png)

**Comment by Naramsim** [comment] 2022-10-19 13:47
Yeah, currently Pokeapi relies on data that uses a different scale. It's like that for each pokemon

**Comment by diekmrcoin** [comment] 2022-10-26 13:43
So, this is a issue that will be solved or is a missleaded bug?

**Comment by DevMike123** [comment] 2022-11-14 03:34
This error can be resolved by dividing the weight of all the Pokemon by 10.

Like for Pikachu,

```js
const wt= pikachu.weight // 60
const weight = wt/10 // 6

```

**Comment by DevMike123** [comment] 2022-11-14 03:36
> So, this is a issue that will be solved or is a missleaded bug?

👆👆👆

**Comment by Naramsim** [comment] 2022-11-14 11:41
Not a bug, won't be changed, sorry

**Closed by Naramsim** 2022-11-14 11:41 UTC
